# Generated by Django 2.1.7 on 2019-03-16 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190314_0302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iplocation',
            name='id',
        ),
        migrations.AlterField(
            model_name='iplocation',
            name='ip_network',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
