# Generated by Django 2.1.7 on 2019-03-18 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190316_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iplocation',
            name='latitude',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='iplocation',
            name='longitude',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
