# Generated by Django 2.1.7 on 2019-03-18 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190318_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iplocation',
            name='latitude',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='iplocation',
            name='longitude',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
